spring.application.name: bantu-todos
server.servlet.contextPath: ${CONTEXT_PATH:/todos}
logging.level.dev.bantu: ${LOG_LEVEL:DEBUG}

app.package: dev.bantu

app.db:
  tables-prefix: todos
  datasources:
    default:
      url: ${DATABASE_URL}?schema=public
      migration: false
    __TENANT__:
      url: ${DATABASE_URL}?schema=__TENANT__
      migration: true

app.consul.tags: ${CONSUL_TAGS:role=api,prefix=${server.servlet.contextPath}}

spring.config.import:
  - classpath:application-foundation.yml
  - classpath:openapi.yml

---
spring.config.activate.on-profile: prod | production | prd
app.consul.discovery: true
app.nats.enabled: true
app.nats.url: ${NATS_URL}
app.nats.queue: bantu-service
