app.openapi:
  info:
    title: Bantu Todos API
    version: ${service-version}
    description: Simple todos service for educational purposes
    contact:
      email: tribe@bantu.dev
      name: The Bantu team
      url: https://developers.bantu.dev
  security:
    basicAuth: true
