name: default

on:
  push:
    branches-ignore:
      - main
      
env:
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_VERSION: ${{ github.run_number }}
  PRV_MAVEN_URL: https://maven.pkg.github.com/soffa-io/artifacts,https://maven.pkg.github.com/startupstation/artifacts
  PRV_MAVEN_USER: ${{ github.actor }}
  PRV_MAVEN_PASSWORD: ${{ secrets.ARTIFACTS_TOKEN }}

jobs:
  check:
    runs-on: ubuntu-latest
    container: gradle:latest
    steps:
      - uses: actions/checkout@v2
      - name: Check branch
        run: |
          gradle check
